var News = require('../news/news-model');
var NSentiment = require('../sentiment/news-sentiment-model');
var Twitter = require('../twitter/twitter-model');
var Users = require('../users/users-model');
// var Finance = require('../finance/finance-model');



//sample news sentiment output from API call:

 var news = {
  "status": "OK",
  "usage": "By accessing AlchemyAPI or using information generated by AlchemyAPI, you are agreeing to be bound by the AlchemyAPI Terms of Use: http://www.alchemyapi.com/company/terms.html",
  "url": "",
  "totalTransactions": "2",
  "language": "english",
  "entities": [
    {
      "type": "Person",
      "relevance": "0.89066",
      "sentiment": {
        "type": "positive",
        "score": "0.234428",
        "mixed": "1"
      },
      "count": "7",
      "text": "Elliot Turner"
    },
    {
      "type": "PrintMedia",
      "relevance": "0.252507",
      "sentiment": {
        "type": "neutral"
      },
      "count": "1",
      "text": "PR Newswire"
    },
    {
      "type": "Company",
      "relevance": "0.233257",
      "sentiment": {
        "type": "positive",
        "score": "0.260944"
      },
      "count": "1",
      "text": "Walmart"
    },
    {
      "type": "Company",
      "relevance": "0.211686",
      "sentiment": {
        "type": "positive",
        "score": "0.274219"
      },
      "count": "1",
      "text": "AlchemyAPI"
    },
    {
      "type": "Technology",
      "relevance": "0.163204",
      "sentiment": {
        "type": "neutral"
      },
      "count": "1",
      "text": "iPhone."
    },
    {
      "type": "Quantity",
      "relevance": "0.163204",
      "sentiment": {
        "type": "neutral"
      },
      "count": "1",
      "text": "three years"
    }
  ]
}






NSentiment.find().exec()
.then(function(results) {
  if (results.length === 0) {
    News.create({
      // title: results.title, 
      // ..... insert data here
    })
  }
});